"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](black)\
$os\
$username\
[î‚°](bg:yellow fg:black)\
$directory\
[î‚°](fg:yellow bg:green)\
$git_branch\
$git_status\
[î‚°](fg:green bg:cyan)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
[î‚°](fg:cyan bg:blue)\
$cmd_duration\
[î‚´ ](fg:blue)\
$line_break$character"""


[os]
disabled = false
style = "bg:black fg:white"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "î˜Ÿ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = true
style_user = "bg:black fg:white"
style_root = "bg:black fg:red bold"
format = '[ $user ]($style)'

[directory]
style = "fg:black bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ó°Œ¾"
read_only_style = "fg:black bg:yellow"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[git_branch]
symbol = "ï˜"
style = "bg:green"
format = '[[ $symbol $branch ](fg:black bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:black bg:green)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:cyan"
format ='[[ $symbol( $version) ](fg:black bg:cyan)]($style)'
[c]
symbol = "î˜ "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[rust]
symbol = "î¨"
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[golang]
symbol = "î˜§"
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[java]
symbol = "î‰– "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[python]
symbol = "î˜†"
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:cyan"
format = '[[ $symbol( $context) ](fg:black bg:cyan)]($style)'

[bun]
format = 'via [ğŸ” $version](bold green) '

# --- Utilidades --- 
[cmd_duration]
min_time = 2_000
style = "bg:blue fg:black"
format = '[[ ó±¦Ÿ $duration ]($style)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ï²](bold fg:green)'
error_symbol = '[âœ—](bold fg:red)'


vimcmd_symbol = '[V](bold fg:green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_symbol = '[ï´](bold fg:purple)'
vimcmd_visual_symbol = '[ï´](bold fg:magenta)'
